-- MySQL Script generated by MySQL Workbench
-- Sat Mar  3 01:41:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bolao_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bolao_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bolao_db` DEFAULT CHARACTER SET utf8 ;
USE `bolao_db` ;

-- -----------------------------------------------------
-- Table `bolao_db`.`COMPETICAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`COMPETICAO` (
  `ID_COMPETICAO` INT NOT NULL AUTO_INCREMENT,
  `NOME_COMPETICAO` VARCHAR(200) NOT NULL,
  `DATA_INICIO_COMPETICAO` DATE NOT NULL,
  `DATA_TERMINO_COMPETICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_COMPETICAO`),
  UNIQUE INDEX `ID_COMPETICAO_UNIQUE` (`ID_COMPETICAO` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`LIGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`LIGA` (
  `ID_LIGA` INT NOT NULL AUTO_INCREMENT,
  `ID_COMPETICAO` INT NOT NULL,
  `NOME_LIGA` VARCHAR(150) NOT NULL,
  `DATA_CRIACAO_LIGA` DATETIME NULL,
  PRIMARY KEY (`ID_LIGA`),
  UNIQUE INDEX `ID_LIGA_UNIQUE` (`ID_LIGA` ASC),
  INDEX `FK_ID_COMPETICAO_idx` (`ID_COMPETICAO` ASC),
  CONSTRAINT `FK_ID_COMPETICAO`
    FOREIGN KEY (`ID_COMPETICAO`)
    REFERENCES `bolao_db`.`COMPETICAO` (`ID_COMPETICAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL,
  `ID_USUARIO_FIREBASE` VARCHAR(150) NOT NULL,
  `NOME_USUARIO` VARCHAR(150) NOT NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`USUARIO_LIGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`USUARIO_LIGA` (
  `ID_USUARIO_LIGA` INT UNSIGNED NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  `ID_LIGA` INT NOT NULL,
  `DATA_ENTRADA_LIGA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_USUARIO_LIGA`),
  INDEX `FK_ID_USUARIO_idx` (`ID_USUARIO` ASC),
  INDEX `FK_ID_LIGA_idx` (`ID_LIGA` ASC),
  CONSTRAINT `FK_ID_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `bolao_db`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_LIGA`
    FOREIGN KEY (`ID_LIGA`)
    REFERENCES `bolao_db`.`LIGA` (`ID_LIGA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`CLUBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`CLUBE` (
  `ID_CLUBE` INT NOT NULL,
  `NOME_CLUBE` VARCHAR(100) NOT NULL,
  `NOME_LOGO_CLUBE` VARCHAR(45) NULL,
  `PAIS_CLUBE` VARCHAR(45) NULL,
  `UF_CLUBE` VARCHAR(2) NULL,
  PRIMARY KEY (`ID_CLUBE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`JOGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`JOGO` (
  `ID_JOGO` INT NOT NULL,
  `ID_COMPETICAO` INT NOT NULL,
  `ID_CLUBE_MANDANTE` INT NOT NULL,
  `ID_CLUBE_VISITANTE` INT NOT NULL,
  `DATA_JOGO` DATETIME NOT NULL,
  `GOLS_MANDANTE` INT NULL,
  `GOLS_VISITANTE` INT NULL,
  PRIMARY KEY (`ID_JOGO`),
  INDEX `FK_COMPETICAO_idx` (`ID_COMPETICAO` ASC),
  INDEX `FK_MANDANTE_idx` (`ID_CLUBE_MANDANTE` ASC),
  INDEX `FK_VISITANTE_idx` (`ID_CLUBE_VISITANTE` ASC),
  CONSTRAINT `FK_COMPETICAO`
    FOREIGN KEY (`ID_COMPETICAO`)
    REFERENCES `bolao_db`.`COMPETICAO` (`ID_COMPETICAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MANDANTE`
    FOREIGN KEY (`ID_CLUBE_MANDANTE`)
    REFERENCES `bolao_db`.`CLUBE` (`ID_CLUBE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_VISITANTE`
    FOREIGN KEY (`ID_CLUBE_VISITANTE`)
    REFERENCES `bolao_db`.`CLUBE` (`ID_CLUBE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bolao_db`.`PALPITE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bolao_db`.`PALPITE` (
  `ID_PALPITE` INT NOT NULL,
  `ID_JOGO` INT NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  `GOLS_MANDANTE` INT NULL,
  `GOLS_VISITANTE` INT NULL,
  PRIMARY KEY (`ID_PALPITE`),
  INDEX `FK_JOGO_idx` (`ID_JOGO` ASC),
  INDEX `FK_USUARIO_idx` (`ID_USUARIO` ASC),
  CONSTRAINT `FK_JOGO`
    FOREIGN KEY (`ID_JOGO`)
    REFERENCES `bolao_db`.`JOGO` (`ID_JOGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `bolao_db`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
